services:
  - type: web
    name: nutrigen-bot-backend
    env: node
    buildCommand: cd backend/functions && npm install
    startCommand: cd backend/functions && node index.js
    envVars:
      - key: NODE_ENV
        value: production
    
  - type: web
    name: nutrigen-bot-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production